/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AutorizacaoSlugRouteImport } from './routes/autorizacao.$slug'
import { Route as AdminAuthRouteImport } from './routes/admin._auth'
import { Route as AdminAuthVendedoresRouteImport } from './routes/admin._auth.vendedores'
import { Route as AdminAuthTesteWhatsappRouteImport } from './routes/admin._auth.teste-whatsapp'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth.dashboard'
import { Route as AdminAuthConfiguracoesRouteImport } from './routes/admin._auth.configuracoes'
import { Route as AdminAuthAutorizacoesRouteImport } from './routes/admin._auth.autorizacoes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizacaoSlugRoute = AutorizacaoSlugRouteImport.update({
  id: '/autorizacao/$slug',
  path: '/autorizacao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthVendedoresRoute = AdminAuthVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthTesteWhatsappRoute = AdminAuthTesteWhatsappRouteImport.update({
  id: '/teste-whatsapp',
  path: '/teste-whatsapp',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthConfiguracoesRoute = AdminAuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAutorizacoesRoute = AdminAuthAutorizacoesRouteImport.update({
  id: '/autorizacoes',
  path: '/autorizacoes',
  getParentRoute: () => AdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/teste-whatsapp': typeof AdminAuthTesteWhatsappRoute
  '/admin/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/teste-whatsapp': typeof AdminAuthTesteWhatsappRoute
  '/admin/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/_auth/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/teste-whatsapp': typeof AdminAuthTesteWhatsappRoute
  '/admin/_auth/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/autorizacao/$slug'
    | '/admin/'
    | '/admin/autorizacoes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/teste-whatsapp'
    | '/admin/vendedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/autorizacao/$slug'
    | '/admin/autorizacoes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/teste-whatsapp'
    | '/admin/vendedores'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/admin/_auth'
    | '/autorizacao/$slug'
    | '/admin/'
    | '/admin/_auth/autorizacoes'
    | '/admin/_auth/configuracoes'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/teste-whatsapp'
    | '/admin/_auth/vendedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AutorizacaoSlugRoute: typeof AutorizacaoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizacao/$slug': {
      id: '/autorizacao/$slug'
      path: '/autorizacao/$slug'
      fullPath: '/autorizacao/$slug'
      preLoaderRoute: typeof AutorizacaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/vendedores': {
      id: '/admin/_auth/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminAuthVendedoresRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/teste-whatsapp': {
      id: '/admin/_auth/teste-whatsapp'
      path: '/teste-whatsapp'
      fullPath: '/admin/teste-whatsapp'
      preLoaderRoute: typeof AdminAuthTesteWhatsappRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/configuracoes': {
      id: '/admin/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAuthConfiguracoesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/autorizacoes': {
      id: '/admin/_auth/autorizacoes'
      path: '/autorizacoes'
      fullPath: '/admin/autorizacoes'
      preLoaderRoute: typeof AdminAuthAutorizacoesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthAutorizacoesRoute: typeof AdminAuthAutorizacoesRoute
  AdminAuthConfiguracoesRoute: typeof AdminAuthConfiguracoesRoute
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthTesteWhatsappRoute: typeof AdminAuthTesteWhatsappRoute
  AdminAuthVendedoresRoute: typeof AdminAuthVendedoresRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthAutorizacoesRoute: AdminAuthAutorizacoesRoute,
  AdminAuthConfiguracoesRoute: AdminAuthConfiguracoesRoute,
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthTesteWhatsappRoute: AdminAuthTesteWhatsappRoute,
  AdminAuthVendedoresRoute: AdminAuthVendedoresRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AutorizacaoSlugRoute: AutorizacaoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
