/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AutorizacaoSlugRouteImport } from './routes/autorizacao.$slug'
import { Route as AdminAuthVendedoresRouteImport } from './routes/admin._auth.vendedores'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth.dashboard'
import { Route as AdminAuthAutorizacoesRouteImport } from './routes/admin._auth.autorizacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizacaoSlugRoute = AutorizacaoSlugRouteImport.update({
  id: '/autorizacao/$slug',
  path: '/autorizacao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthVendedoresRoute = AdminAuthVendedoresRouteImport.update({
  id: '/admin/_auth/vendedores',
  path: '/admin/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/admin/_auth/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthAutorizacoesRoute = AdminAuthAutorizacoesRouteImport.update({
  id: '/admin/_auth/autorizacoes',
  path: '/admin/autorizacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autorizacao/$slug': typeof AutorizacaoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/autorizacoes': typeof AdminAuthAutorizacoesRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/vendedores': typeof AdminAuthVendedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autorizacao/$slug'
    | '/admin/'
    | '/admin/autorizacoes'
    | '/admin/dashboard'
    | '/admin/vendedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autorizacao/$slug'
    | '/admin'
    | '/admin/autorizacoes'
    | '/admin/dashboard'
    | '/admin/vendedores'
  id:
    | '__root__'
    | '/'
    | '/autorizacao/$slug'
    | '/admin/'
    | '/admin/_auth/autorizacoes'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/vendedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorizacaoSlugRoute: typeof AutorizacaoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuthAutorizacoesRoute: typeof AdminAuthAutorizacoesRoute
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthVendedoresRoute: typeof AdminAuthVendedoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizacao/$slug': {
      id: '/autorizacao/$slug'
      path: '/autorizacao/$slug'
      fullPath: '/autorizacao/$slug'
      preLoaderRoute: typeof AutorizacaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/vendedores': {
      id: '/admin/_auth/vendedores'
      path: '/admin/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminAuthVendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/autorizacoes': {
      id: '/admin/_auth/autorizacoes'
      path: '/admin/autorizacoes'
      fullPath: '/admin/autorizacoes'
      preLoaderRoute: typeof AdminAuthAutorizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorizacaoSlugRoute: AutorizacaoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuthAutorizacoesRoute: AdminAuthAutorizacoesRoute,
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthVendedoresRoute: AdminAuthVendedoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
