// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubrpwkudeikhdfprqve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YnJwd2t1ZGVpa2hkZnBycXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0MjY5NzAsImV4cCI6MjEwMDAwMjk3MH0.D2w8GZBTwcZqVtnlZccgHtm31vTnXvvIyJlyT4gxnFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});